# config.yaml
model: StockMixer   # 可选: StockMixer, StockTransformer
data_path: ./dataset
market_name: NASDAQ
relation_name: wikidata
stock_num: 1026
lookback_length: 16
epochs: 100
valid_index: 756
test_index: 1008
fea_num: 5
market_num: 20
steps: 1
learning_rate: 0.001
alpha: 0.1
scale_factor: 3
activation: GELU
patience: 10